feat: sm-26 - create user registration api along with cloudinary and multer config setup
VatsalDave2102/social-media-backend pull request #1
Opened 2024-08-02 07:11 UTC by RiteshAdwani

This PR introduces user registration functionality for user authentication in our social media backend and also some changes in the boiler plate code. The key features include:
1. File upload handling with Multer for the profile picture.
2. Integration with Cloudinary for secure and efficient image storage.
3. Data validation using Zod schemas, ensuring that incoming data meets our requirements.
4. Proper database interaction to save the new user.
5. Generation of both access and refresh tokens upon successful registration.
6. Sending back a well-structured response with user data and tokens.
7. Implemented centralized environment variable management for improved configuration and type safety.

2024-08-05 09:14 UTC, VatsalDave2102 commented on src/middlewares/verifyToken.ts
> +      return res.status(StatusCodes.UNAUTHORIZED).json({
Error response could be thrown using errorHandler middleware

2024-08-05 09:31 UTC, VatsalDave2102 requested changes

2024-08-05 09:31 UTC, VatsalDave2102 commented on src/middlewares/verifyToken.ts
> +      });
Error response could be thrown using errorHandler middleware

2024-08-05 09:40 UTC, VatsalDave2102 commented on src/utils/token.ts
> +    throw new AppError('ACCESS TOKEN SECRET KEY is not defined', StatusCodes.INTERNAL_SERVER_ERROR);
Could add a condition to show this only in development environment

2024-08-12 04:25 UTC, VatsalDave2102 approved these changes
Looks good, approved.

2024-08-27 08:33 UTC, kashyap27102 approved these changes

2024-08-28 05:57 UTC, svipulc approved these changes

2024-08-28 06:05 UTC, merged